### ISSUE TITLE
Number of channels and efficiency improvement

### ISSUE THREAD

**Issue by yangxiao5201** [lbf4616/PixelLink-with-MobileNet-V2#1]
Thanks for your nice work!
Two questions:
1. The number of output channels (in each block) are different in mobilenet-v2 and vgg-16. How do you deal with that?
2. Have you evaluated the improvement of efficiency (FPS and memory occupancy)?
Thanks!

谢谢你的工作！两个问题请教：
1. VGG-16和mobilenet-v2中，每个block的输出的channel数量不同，这里end_points的通道数量是怎么处理的？
2. 有没有测试过改为mobilenet-v2之后pixel link的耗时和内存占用的提升效果呢？
非常感谢！

**Comment by lbf4616** [comment]
Thanks for your questions.
1. As intruduced in the orginial Pixlelink paper. They used four outputs from different layers of VGG16, and then used another cov with the number of 2 or 16 for each outputs. So, the different numbers channels between the mb2 and vgg16 doesn't effect the structure of the net.
2. We didn't test the FPS and memory occupancy yet, however, the size of the pixel_link_vgg16 model is about 240MB, the pixel_link_mb2 is about 26MB.

**Comment by yangxiao5201** [comment]
Oh I see. Thanks a lot!
Another question. In the definition of basenet, the structure is a little bit different from the original mb2. The 28×28×* sized feature maps goes through 6 inverted bottlenecks in the original mb2, while just 3 in your codes. How do you choose the structure, and the position of "end_points['conv3']" and "end_points['conv4']"?

**Comment by lbf4616** [comment]
conv3 and conv4 was choosen by the previous layer of the downsampling layer. The stucture is followed by https://arxiv.org/pdf/1801.04381.pdf. Table 2. Please check it, and care about the parameter _n_ .

**Comment by yangxiao5201** [comment]
I got it. Thanks!
